language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
    - rust: nightly
      env: FEATURES="--features nightly"
    - rust: stable
      env: RUN=FMT
      before_script: rustup component add rustfmt-preview
      script: cargo fmt --all -- --write-mode diff
script:
  - cargo test $FEATURES
